name: translate_helper_3
description: Translate Helper 3

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-172.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  translator: ^0.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true